### ISSUE TITLE
why dont work?

### ISSUE THREAD

**Issue by cesarandres123** [DavidAmunga/Forth#1]
hi my friend.
the proyect does not work correctly.
at the point where I call the driver nothing happens, he simply says in a toast "fail"
i connect it correctly to firebase. 
and activate the api google maps, directions, places, geocoding and geolocation.

What do I need to make it work?

**Comment by senhor-R** [comment]
Did you use the correct key?

2018-04-07 23:09 GMT-03:00 cesarandres123 <notifications@github.com>:

**Comment by senhor-R** [comment]
https://console.cloud.google.com/apis/

select your project

2018-04-08 1:40 GMT-03:00 Mr. R 0101 <mr.radamis@gmail.com>:

**Comment by cesarandres123** [comment]
i use a Android key (auto created by Google Service)

**Comment by cesarandres123** [comment]
i solved change the api key..
